# Generated by Django 6.0.6 on 2026-06-28 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('info', models.TextField(verbose_name='information')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('room_count', models.PositiveIntegerField(default=0, verbose_name='Room`s count')),
                ('people_count', models.PositiveIntegerField(default=0, verbose_name='People`s count')),
                ('square', models.PositiveIntegerField(default=0, verbose_name='Square')),
                ('price_by_day', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Payment')),
                ('rating', models.PositiveIntegerField(verbose_name='Rating')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Is booked')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Будинок',
                'verbose_name_plural': 'Будинки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField(verbose_name='Arrival date')),
                ('departure_date', models.DateField(verbose_name='Departure date')),
                ('status', models.CharField(choices=[('in_progress', 'в обробці'), ('confirmed', 'підтверджено'), ('canceled', 'скасовано')], default='in_progress', max_length=20, verbose_name='Status')),
                ('comment', models.CharField(blank=True, max_length=150, null=True, verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.housemodel', verbose_name='House')),
            ],
            options={
                'verbose_name': 'Бронювання',
                'verbose_name_plural': 'Бронювання',
                'ordering': ['-created_at'],
            },
        ),
    ]
