# Generated by Django 6.0.6 on 2026-07-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='user_first_name',
            field=models.CharField(default='name', max_length=50, verbose_name='First name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='user_last_name',
            field=models.CharField(default='last name', max_length=50, verbose_name='Last name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='user_phone_number',
            field=models.CharField(default='phone', max_length=20, verbose_name='Phone number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В обробці'), ('confirmed', 'Підтверджено'), ('done', 'Виконано'), ('canceled', 'Скасовано')], default='in_progress', max_length=20, verbose_name='Status'),
        ),
    ]
